version: '3.9'

services:
  backend:
    container_name: django-app
    image: lauraokafor/project:backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    container_name: react-app
    image: lauraokafor/project:frontend
    # build: /home/ubuntu/ComputexFrontend
    ports:
      - "5173:5173"

  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=recipe
    volumes:
      - ddata:/var/lib/postgresql/data

volumes:
  ddata: