- name: Configure Database
  hosts: database
  become: yes
  tasks:
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Copy Docker Compose File
      copy:
        src: /Users/m1/Documents/devops-fullstack-deployment/devops-fullstack-deployment/React-Django-App/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Start PostgreSQL Container
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu