
[frontend]
vm_frontend ansible_host=98.83.159.137 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem

[backend]
vm_backend ansible_host=3.91.22.45 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem

[database]
vm_database ansible_host=54.236.13.236 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem