
[frontend]
vm_frontend ansible_host=34.229.105.248 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem

[backend]
vm_backend ansible_host=18.206.179.202 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem

[database]
vm_database ansible_host=18.234.229.60 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem