
[frontend]
vm_frontend ansible_host=52.55.60.18 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem

[backend]
vm_backend ansible_host=52.203.188.100 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem

[database]
vm_database ansible_host=54.237.247.18 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/m1/Downloads/project.pem